#!/bin/bash

echo "🌙 Moon Dev - Stripe Setup Guide"
echo "================================"
echo ""
echo "Follow these steps to get your Stripe keys:"
echo ""
echo "1. Go to: https://dashboard.stripe.com/register"
echo "   Create an account if you don't have one"
echo ""
echo "2. Get your Secret Key:"
echo "   → https://dashboard.stripe.com/test/apikeys"
echo "   → Click 'Reveal test key'"
echo "   → Copy the key starting with 'sk_test_'"
echo ""
echo "3. Create Products & Prices:"
echo "   → https://dashboard.stripe.com/test/products"
echo "   → Click '+ Add product'"
echo ""
echo "   Product 1: Builder Plan"
echo "   - Price: \$49/month (recurring)"
echo "   - Copy the price ID (starts with 'price_')"
echo ""
echo "   Product 2: Desk Plan"
echo "   - Price: \$149/month (recurring)"
echo "   - Copy the price ID"
echo ""
echo "   Product 3: Fund Plan"
echo "   - Price: \$299/month (recurring)"
echo "   - Copy the price ID"
echo ""
echo "4. Set up Webhook:"
echo "   → https://dashboard.stripe.com/test/webhooks"
echo "   → Click '+ Add endpoint'"
echo "   → Endpoint URL: http://localhost:8011/billing/webhook"
echo "   → Select events:"
echo "     - checkout.session.completed"
echo "     - customer.subscription.created"
echo "     - customer.subscription.updated"
echo "     - customer.subscription.deleted"
echo "   → Copy the signing secret (starts with 'whsec_')"
echo ""
echo "5. Create Discord Webhook:"
echo "   → Open Discord Server Settings"
echo "   → Integrations → Webhooks → New Webhook"
echo "   → Copy webhook URL"
echo ""
echo "6. Update .env file with all these values"
echo ""
echo "Then run: ./deploy.sh"
echo ""
